/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedInstructorRouteImport } from './routes/_authenticated/instructor'
import { Route as AuthenticatedSessionRouteImport } from './routes/_authenticated/session'
import { Route as ApiSttRouteImport } from './routes/api/stt'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as AuthenticatedInstructorSessionIdRouteImport } from './routes/_authenticated/instructor/$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedInstructorRoute = AuthenticatedInstructorRouteImport.update({
  id: '/instructor',
  path: '/instructor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSessionRoute = AuthenticatedSessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiSttRoute = ApiSttRouteImport.update({
  id: '/api/stt',
  path: '/api/stt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedInstructorSessionIdRoute =
  AuthenticatedInstructorSessionIdRouteImport.update({
    id: '/$sessionId',
    path: '/$sessionId',
    getParentRoute: () => AuthenticatedInstructorRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/instructor': typeof AuthenticatedInstructorRouteWithChildren
  '/session': typeof AuthenticatedSessionRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/instructor/$sessionId': typeof AuthenticatedInstructorSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/instructor': typeof AuthenticatedInstructorRouteWithChildren
  '/session': typeof AuthenticatedSessionRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/instructor/$sessionId': typeof AuthenticatedInstructorSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/instructor': typeof AuthenticatedInstructorRouteWithChildren
  '/_authenticated/session': typeof AuthenticatedSessionRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/_authenticated/instructor/$sessionId': typeof AuthenticatedInstructorSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/instructor'
    | '/session'
    | '/api/stt'
    | '/api/tts'
    | '/instructor/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/instructor'
    | '/session'
    | '/api/stt'
    | '/api/tts'
    | '/instructor/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/instructor'
    | '/_authenticated/session'
    | '/api/stt'
    | '/api/tts'
    | '/_authenticated/instructor/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiSttRoute: typeof ApiSttRoute
  ApiTtsRoute: typeof ApiTtsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/instructor': {
      id: '/_authenticated/instructor'
      path: '/instructor'
      fullPath: '/instructor'
      preLoaderRoute: typeof AuthenticatedInstructorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/session': {
      id: '/_authenticated/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof AuthenticatedSessionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/stt': {
      id: '/api/stt'
      path: '/api/stt'
      fullPath: '/api/stt'
      preLoaderRoute: typeof ApiSttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/instructor/$sessionId': {
      id: '/_authenticated/instructor/$sessionId'
      path: '/$sessionId'
      fullPath: '/instructor/$sessionId'
      preLoaderRoute: typeof AuthenticatedInstructorSessionIdRouteImport
      parentRoute: typeof AuthenticatedInstructorRoute
    }
  }
}

interface AuthenticatedInstructorRouteChildren {
  AuthenticatedInstructorSessionIdRoute: typeof AuthenticatedInstructorSessionIdRoute
}

const AuthenticatedInstructorRouteChildren: AuthenticatedInstructorRouteChildren =
  {
    AuthenticatedInstructorSessionIdRoute:
      AuthenticatedInstructorSessionIdRoute,
  }

const AuthenticatedInstructorRouteWithChildren =
  AuthenticatedInstructorRoute._addFileChildren(
    AuthenticatedInstructorRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedInstructorRoute: typeof AuthenticatedInstructorRouteWithChildren
  AuthenticatedSessionRoute: typeof AuthenticatedSessionRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedInstructorRoute: AuthenticatedInstructorRouteWithChildren,
  AuthenticatedSessionRoute: AuthenticatedSessionRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiSttRoute: ApiSttRoute,
  ApiTtsRoute: ApiTtsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
